# Generated by Django 5.2.3 on 2025-06-29 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the credit card (e.g., 'Nubank Credit Card')",
                        max_length=100,
                    ),
                ),
                (
                    "close_date",
                    models.PositiveIntegerField(
                        help_text="Day of the month when the billing cycle closes (1-31)"
                    ),
                ),
                (
                    "due_date",
                    models.PositiveIntegerField(
                        help_text="Day of the month when payment is due (1-31)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the credit card was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the credit card was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the credit card is active and can be used for transactions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner of this credit card",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Card",
                "verbose_name_plural": "Credit Cards",
                "db_table": "credit_cards",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="credit_card_user_id_c42b58_idx",
                    ),
                    models.Index(
                        fields=["close_date"], name="credit_card_close_d_549fb3_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="credit_card_due_dat_881872_idx"
                    ),
                ],
            },
        ),
    ]
