# Generated by Django 5.2.3 on 2025-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                help_text="Type of transactions this category is used for",
                max_length=10,
            ),
        ),
    ]
