# Generated by Django 5.2.3 on 2025-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2025-07-13 13:00:00-03:00",
                help_text="The date and time the transaction was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time the transaction was last updated",
            ),
        ),
    ]
