# Generated by Django 5.2.3 on 2025-12-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_transactions",
                to="accounts.category",
            ),
        ),
    ]
