# Generated by Django 5.2.3 on 2025-12-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_importedreport_account_importedreport_credit_card"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="creditcard",
            name="credit_card_close_d_549fb3_idx",
        ),
        migrations.RemoveIndex(
            model_name="creditcard",
            name="credit_card_due_dat_881872_idx",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="close_date",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="charge_at_card",
        ),
    ]
