# Generated by Django 5.2.3 on 2026-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_transaction_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="MD5 hash of amount, description, and occurred_at for duplicate detection",
                max_length=32,
                null=True,
            ),
        ),
    ]
