# Generated by Django 5.2.3 on 2026-01-18 14:29

import hashlib

from django.db import migrations


def populate_transaction_hash(apps, schema_editor):
    """Populate hash field for existing transactions."""
    Transaction = apps.get_model("accounts", "Transaction")

    for transaction in Transaction.objects.all():
        amount_str = str(transaction.amount)
        description_str = transaction.description or ""
        occurred_at_str = transaction.occurred_at.isoformat() if transaction.occurred_at else ""

        hash_input = f"{amount_str}|{description_str}|{occurred_at_str}"
        transaction.hash = hashlib.md5(hash_input.encode("utf-8")).hexdigest()
        transaction.save(update_fields=["hash"])


def reverse_populate_transaction_hash(apps, schema_editor):
    """Reverse migration - set hash to None."""
    Transaction = apps.get_model("accounts", "Transaction")
    Transaction.objects.all().update(hash=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_transaction_hash"),
    ]

    operations = [
        migrations.RunPython(
            populate_transaction_hash,
            reverse_populate_transaction_hash,
        ),
    ]
