# Generated by Django 5.2.3 on 2026-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_importedreport_photo_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedreport",
            name="positive_as_expense",
            field=models.BooleanField(
                default=True,
                help_text="If True, positive amounts are treated as expenses; if False, as income",
            ),
        ),
    ]
