# Generated by Django 5.2.3 on 2026-03-03 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_add_positive_as_expense_to_imported_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly budget limit amount",
                        max_digits=12,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this budget is currently active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the budget was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the budget was last updated",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category this budget applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="accounts.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner of this budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budgets",
                "ordering": ["category__name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="budgets_user_id_ce81fb_idx"
                    )
                ],
                "unique_together": {("user", "category")},
            },
        ),
    ]
