# Generated by Django 5.2.3 on 2026-05-02 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_installmentplan_transaction_installment_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ignore_duplicates",
            field=models.BooleanField(
                default=False,
                help_text="Whether this transaction should be excluded from duplicate detection",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "ignore_duplicates"], name="txn_user_ignore_dup_idx"
            ),
        ),
    ]
