# Generated by Django 5.2.3 on 2026-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_transaction_ignore_duplicates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="MD5 hash of amount, description, and occurred_at for duplicate detection",
                max_length=36,
                null=True,
            ),
        ),
    ]
