version: '3.8'
services:
  app:
    build: .
    command: ["/bin/sh", "/app/entrypoint.sh"]
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres_data:
