# Generated by Django 5.2.3 on 2025-12-26 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aiclassifierinstruction",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_instruction"
            ),
        ),
    ]
