# Generated by Django 5.2.3 on 2025-06-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_category_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="color",
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
    ]
