# Generated by Django 5.2.3 on 2025-12-22 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_category_data(apps, schema_editor):
    """Clear existing category and transaction data for fresh start."""
    Category = apps.get_model("accounts", "Category")
    Transaction = apps.get_model("accounts", "Transaction")
    
    Transaction.objects.filter(category__isnull=False).update(category=None)
    Transaction.objects.filter(subcategory__isnull=False).update(subcategory=None)
    
    Category.objects.all().delete()


def reverse_clear_category_data(apps, schema_editor):
    """Reverse migration - nothing to restore."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_transaction_created_at_transaction_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_category_data, reverse_clear_category_data),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subcategory (e.g., 'Fuel', 'Maintenance', 'Groceries')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the subcategory"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the subcategory was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the subcategory was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the subcategory is active and can be used for transactions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
                "db_table": "subcategories",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="categories_parent__7983b2_idx",
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("user", "name", "transaction_type")},
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                help_text="The parent category this subcategory belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="accounts.category",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="user",
            field=models.ForeignKey(
                help_text="The owner of this subcategory",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="accounts.subcategory",
            ),
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["user", "is_active"], name="subcategori_user_id_6faba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["category"], name="subcategori_categor_c498e4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("user", "name", "category")},
        ),
    ]
