# Generated by Django 5.2.3 on 2025-12-22 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_transaction_subcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("PROCESSING", "Processing"),
                            ("IMPORTED", "Imported"),
                            ("FAILED", "Failed"),
                        ],
                        default="SENT",
                        help_text="Current status of the import",
                        max_length=20,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename of the uploaded CSV file",
                        max_length=255,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Storage path/key returned by file storage service",
                        max_length=500,
                    ),
                ),
                (
                    "handler_type",
                    models.CharField(
                        blank=True,
                        help_text="Handler class name used for processing (e.g., BancoInterCreditCardCsvHandler)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "failed_reason",
                    models.TextField(
                        blank=True,
                        help_text="Error details if import failed",
                        null=True,
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of successfully imported transactions",
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0, help_text="Number of failed transactions"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        default=list,
                        help_text="List of error messages for failed transactions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the import was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the import was last updated",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when processing completed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who uploaded this import",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imported Report",
                "verbose_name_plural": "Imported Reports",
                "db_table": "imported_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="imported_re_user_id_955af0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="imported_re_status_2c48e5_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="imported_re_created_c802ab_idx"
                    ),
                ],
            },
        ),
    ]
