# Generated by Django 5.2.3 on 2025-12-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_transaction_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedreport",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account to associate with all imported transactions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_reports",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="importedreport",
            name="credit_card",
            field=models.ForeignKey(
                blank=True,
                help_text="Credit card to associate with all imported transactions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_reports",
                to="accounts.creditcard",
            ),
        ),
    ]
