# Generated by Django 5.2.3 on 2025-12-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_creditcard_credit_card_close_d_549fb3_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the cash flow view (e.g., 'Monthly P&L', 'Annual Summary')",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the view was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the view was last updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner of this cash flow view",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow View",
                "verbose_name_plural": "Cash Flow Views",
                "db_table": "cash_flow_views",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the result line (e.g., 'Gross Margin', 'Net Result')",
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Position of this result within the view (used for ordering and calculation)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the result was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the result was last updated",
                    ),
                ),
                (
                    "cash_flow_view",
                    models.ForeignKey(
                        help_text="The cash flow view this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="accounts.cashflowview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow Result",
                "verbose_name_plural": "Cash Flow Results",
                "db_table": "cash_flow_results",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the group (e.g., 'Revenue', 'Operating Costs')",
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Position of this group within the view (used for ordering and result calculations)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the group was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the group was last updated",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categories included in this group",
                        related_name="cash_flow_groups",
                        to="accounts.category",
                    ),
                ),
                (
                    "cash_flow_view",
                    models.ForeignKey(
                        help_text="The cash flow view this group belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="accounts.cashflowview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow Group",
                "verbose_name_plural": "Cash Flow Groups",
                "db_table": "cash_flow_groups",
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="cashflowview",
            index=models.Index(
                fields=["user", "name"], name="cash_flow_v_user_id_93c6d2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cashflowview",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="cashflowresult",
            index=models.Index(
                fields=["cash_flow_view", "position"],
                name="cash_flow_r_cash_fl_1d5fec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowgroup",
            index=models.Index(
                fields=["cash_flow_view", "position"],
                name="cash_flow_g_cash_fl_22ab02_idx",
            ),
        ),
    ]
