# Generated by Django 5.2.3 on 2025-12-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_transaction_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="origin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source of transaction creation (e.g., 'manual', report filename)",
                max_length=255,
            ),
        ),
    ]
